language: go

go:
  - 1.11
  - 1.16.x

before_install:

sudo: false

env:
  - GO111MODULE=on

notifications:
  email:
    recipients:
      - soseek@vip.qq.com
    on_success: always

install:

script:
  - go test -test.short ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
